@startuml Part4

Initialization : Entry - Initialize parameters.
Initialization : Do - Check if system ready and send boot-up msg
Initialization : Exit - Send to PreOperation


Initialization --> PreOperational : Auto transition
PreOperational : Entry - Set LED to blink 1 Hz
PreOperational : Do - Listen for configuration commands
PreOperational : Exit - Execute set operational command
PreOperational --> Initialization : Reset command


PreOperational --> Operational : Set operational command 
Operational : Entry - Start motor control and set LED to stay on
Operational : Do - Control motor
Operational : Exit - Safely stop motor
Operational --> PreOperational : Pre-operational command
Operational --> Initialization : Reset command

state Stopped {
    Stopped : Entry - Stop motor
    Stopped : Do- Wait for command
    Stopped : Exit - Execute command
}

Operational --> Stopped : Fault detected/Auto transition
PreOperational --> Stopped : Fault detected/Auto transition
Stopped --> Initialization : Reset command
Stopped --> PreOperational : Execute command
Stopped --> Operational : Execute command


@enduml